name: Test

on:
  pull_request:
    branches: [master]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clean and install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Show package.json scripts
        run: cat package.json

      - name: Run Cypress Component Tests
        run: npm run test:ci

      - name: Upload tests report (mochawesome)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: raw_reports
